# Generated by Django 6.0.3 on 2026-03-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsxfile",
            name="dbt_sql",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsxfile",
            name="documentation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsxfile",
            name="snowflake_sql",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsxfile",
            name="sttm_file",
            field=models.FileField(blank=True, null=True, upload_to="sttm/"),
        ),
        migrations.AddField(
            model_name="dsxfile",
            name="sttm_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
