# Generated by Django 6.0.3 on 2026-04-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_dsxfile_dbt_sql_dsxfile_documentation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformaticaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="informatica/")),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("sttm_json", models.JSONField(blank=True, null=True)),
                ("snowflake_sql", models.TextField(blank=True, null=True)),
                ("documentation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingestion.batchjob",
                    ),
                ),
            ],
        ),
    ]
